### ISSUE TITLE
Implement game end screen

### ISSUE THREAD

**Issue by jm179796** [NotKieran/DRTN-Fractal#31]

**Comment by NotKieran** [comment]
Currently kills the game after 1 round with error message:

`Exception in thread "LWJGL Application" java.lang.NullPointerException
	at io.github.teamfractal.RoboticonQuest.checkGameEnded(RoboticonQuest.java:253)
	at io.github.teamfractal.RoboticonQuest.nextPhase(RoboticonQuest.java:155)
	at io.github.teamfractal.actors.ResourceMarketActors$2.clicked(ResourceMarketActors.java:177)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
`
